#
# Project settings
#

#_PROJECT_=WFx
PROJECT_ROOT=$(HOME)\code\WFx\src
PROJECT_OBJ_ROOT=$(OBJECT_ROOT)\$(MAKEDIR_RELATIVE_TO_BASEDIR)\$(_PROJECT_MK_PATH)

USE_NATIVE_EH=1
USE_MSVCRT=1
USE_STL=1
USE_DEV11=1
STL_VER=110
URT_VER=4.5

UNICODE=1

C_DEFINES= \
    $(C_DEFINES) \
    /D_UNICODE \
    /DUNICODE \

INCLUDES= \
    $(INCLUDES); \
    $(PROJECT_ROOT); \

MSC_WARNING_LEVEL=/W4 /WX
